"""Migration integrity: upgrade to head, downgrade to base, upgrade again.

If this fails, `downgrade()` in some revision is broken or out of sync with
`upgrade()` — a real risk with 43 autogenerated tables edited by hand.
"""

import pathlib

from alembic import command
from alembic.config import Config

from tests.domain.conftest import requires_db

ROOT = pathlib.Path(__file__).resolve().parents[2]


def _alembic_config() -> Config:
    cfg = Config(str(ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(ROOT / "packages" / "domain" / "migrations"))
    return cfg


@requires_db
def test_migrations_round_trip() -> None:
    cfg = _alembic_config()
    command.downgrade(cfg, "base")
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
    command.upgrade(cfg, "head")  # leave the DB at head for other tests
