"""Migration integrity: upgrade to head, downgrade to base, upgrade again.

If this fails, `downgrade()` in some revision is broken or out of sync with
`upgrade()` — a real risk with 43 autogenerated tables edited by hand.

This test drops every table (`downgrade base`) — with no separate test
database yet (tests/domain/conftest.py), that destroys whatever
`scripts/generate_synthetic_dataset.py` loaded into the shared dev DB and
breaks tests/api, which expects that data to be there. So this test is
opt-in only: set `RUN_DESTRUCTIVE_DB_TESTS=1` to run it, and re-run
`scripts/generate_synthetic_dataset.py` afterwards.
"""

import os
import pathlib

import pytest
from alembic import command
from alembic.config import Config

from tests.domain.conftest import requires_db

ROOT = pathlib.Path(__file__).resolve().parents[2]

requires_opt_in = pytest.mark.skipif(
    os.environ.get("RUN_DESTRUCTIVE_DB_TESTS") != "1",
    reason="wipes all tables in the shared dev DB — set RUN_DESTRUCTIVE_DB_TESTS=1 to run, "
    "then re-run scripts/generate_synthetic_dataset.py",
)


def _alembic_config() -> Config:
    cfg = Config(str(ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(ROOT / "packages" / "domain" / "migrations"))
    return cfg


@requires_db
@requires_opt_in
def test_migrations_round_trip() -> None:
    cfg = _alembic_config()
    command.downgrade(cfg, "base")
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
    command.upgrade(cfg, "head")  # leave the DB at head for other tests
