"""Migration integrity: upgrade to head, downgrade to base, upgrade again.

If this fails, `downgrade()` in some revision is broken or out of sync with
`upgrade()` — a real risk with 43 autogenerated tables edited by hand.

This test drops every table (`downgrade base`) in the isolated test
database (see root `conftest.py`) and then re-seeds it (synthetic dataset +
knowledge ingestion + indexing) so later tests in the same run aren't left
without fixtures. That reseed takes several seconds, so this stays opt-in
(`RUN_DESTRUCTIVE_DB_TESTS=1`) to keep the default `pytest` run fast, not
because it's unsafe to run.
"""

import os
import pathlib

import pytest
from alembic import command
from alembic.config import Config
from tests.legacy.domain.conftest import requires_db

ROOT = pathlib.Path(__file__).resolve().parents[3]

requires_opt_in = pytest.mark.skipif(
    os.environ.get("RUN_DESTRUCTIVE_DB_TESTS") != "1",
    reason="reseeds the test database afterwards, which takes several seconds — set RUN_DESTRUCTIVE_DB_TESTS=1 to run",
)


def _alembic_config() -> Config:
    cfg = Config(str(ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(ROOT / "packages" / "domain" / "migrations"))
    return cfg


@requires_db
@requires_opt_in
def test_migrations_round_trip() -> None:
    import sys

    sys.path.insert(0, str(ROOT))
    from conftest import _seed_if_empty  # root conftest.py

    cfg = _alembic_config()
    try:
        command.downgrade(cfg, "base")
        command.upgrade(cfg, "head")
        command.downgrade(cfg, "base")
        command.upgrade(cfg, "head")
    finally:
        _seed_if_empty()  # leave the DB usable for other tests, win or lose
