"""canonical regulatory schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-11 16:04:53.429319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # required by the `embeddings.embedding` Vector column
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_cases',
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('query_type', sa.Text(), nullable=False),
    sa.Column('review_status', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_evaluation_cases_dataset_version'), 'evaluation_cases', ['dataset_version'], unique=False)
    op.create_index(op.f('ix_evaluation_cases_query_type'), 'evaluation_cases', ['query_type'], unique=False)
    op.create_table('query_traces',
    sa.Column('trace_id', sa.Text(), nullable=False),
    sa.Column('principal', sa.Text(), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trace_id')
    )
    op.create_table('regulations',
    sa.Column('regulation_key', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('authority', sa.Text(), nullable=False),
    sa.Column('jurisdiction', sa.Text(), nullable=False),
    sa.Column('authority_level', sa.Text(), nullable=False),
    sa.Column('data_class', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regulation_key')
    )
    op.create_table('source_artifacts',
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('media_type', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.Text(), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_index(op.f('ix_source_artifacts_source_key'), 'source_artifacts', ['source_key'], unique=False)
    op.create_table('user_feedback',
    sa.Column('trace_id', sa.Text(), nullable=False),
    sa.Column('principal', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_feedback_trace_id'), 'user_feedback', ['trace_id'], unique=False)
    op.create_table('regulation_versions',
    sa.Column('regulation_id', sa.UUID(), nullable=False),
    sa.Column('source_artifact_id', sa.UUID(), nullable=False),
    sa.Column('version_label', sa.Text(), nullable=False),
    sa.Column('series', sa.Text(), nullable=True),
    sa.Column('revision', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parser_name', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.Text(), nullable=True),
    sa.Column('parser_config_hash', sa.Text(), nullable=True),
    sa.Column('parsed_hash', sa.Text(), nullable=True),
    sa.Column('chunker_version', sa.Text(), nullable=True),
    sa.Column('chunker_config_hash', sa.Text(), nullable=True),
    sa.Column('index_schema_version', sa.Integer(), nullable=True),
    sa.Column('amendments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['source_artifacts.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['regulation_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regulation_id', 'version_label', name='uq_regulation_version_label')
    )
    op.create_index(op.f('ix_regulation_versions_regulation_id'), 'regulation_versions', ['regulation_id'], unique=False)
    op.create_index(op.f('ix_regulation_versions_status'), 'regulation_versions', ['status'], unique=False)
    op.create_index('ix_regulation_versions_status_valid', 'regulation_versions', ['status', 'valid_from', 'valid_to'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('source_key', sa.Text(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('git_sha', sa.Text(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['regulation_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_source_key'), 'ingestion_runs', ['source_key'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_status'), 'ingestion_runs', ['status'], unique=False)
    op.create_table('sections',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('parent_section_id', sa.UUID(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('section_number', sa.Text(), nullable=True),
    sa.Column('annex', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('normative', sa.Boolean(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['regulation_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'path', name='uq_section_path_per_version')
    )
    op.create_index(op.f('ix_sections_content_sha256'), 'sections', ['content_sha256'], unique=False)
    op.create_index(op.f('ix_sections_version_id'), 'sections', ['version_id'], unique=False)
    op.create_index('ix_sections_version_ordinal', 'sections', ['version_id', 'ordinal'], unique=False)
    op.create_table('chunks',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('parent_chunk_id', sa.UUID(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('citation_label', sa.Text(), nullable=False),
    sa.Column('chunk_sha256', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['regulation_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'ordinal', name='uq_chunk_ordinal_per_version')
    )
    op.create_index(op.f('ix_chunks_section_id'), 'chunks', ['section_id'], unique=False)
    op.create_index(op.f('ix_chunks_version_id'), 'chunks', ['version_id'], unique=False)
    op.create_index('ix_chunks_version_sha', 'chunks', ['version_id', 'chunk_sha256'], unique=False)
    op.create_table('cross_references',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('from_section_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('target_path', sa.Text(), nullable=False),
    sa.Column('target_regulation_key', sa.Text(), nullable=True),
    sa.Column('resolved_section_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['from_section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['resolved_section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['regulation_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_references_from_section_id'), 'cross_references', ['from_section_id'], unique=False)
    op.create_index(op.f('ix_cross_references_version_id'), 'cross_references', ['version_id'], unique=False)
    op.create_table('figures',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('figure_index', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('image_sha256', sa.Text(), nullable=False),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('figure_type', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['regulation_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_figures_version_id'), 'figures', ['version_id'], unique=False)
    op.create_table('ingestion_events',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_status', sa.Text(), nullable=True),
    sa.Column('to_status', sa.Text(), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_events_run_id'), 'ingestion_events', ['run_id'], unique=False)
    op.create_table('tables',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('table_index', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_method', sa.Text(), nullable=False),
    sa.Column('quality_score', sa.Double(), nullable=False),
    sa.Column('content_sha256', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['regulation_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tables_version_id'), 'tables', ['version_id'], unique=False)
    op.create_table('chunk_embeddings',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'model_name', 'model_version', name='uq_embedding_per_chunk_model')
    )
    op.create_index(op.f('ix_chunk_embeddings_chunk_id'), 'chunk_embeddings', ['chunk_id'], unique=False)
    # ### end Alembic commands ###


    # Cosine HNSW index on the fixed-dimension embedding column (docs/ADR/0019).
    op.execute(
        "CREATE INDEX ix_chunk_embeddings_hnsw_cosine ON chunk_embeddings "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_chunk_embeddings_hnsw_cosine")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_embeddings_chunk_id'), table_name='chunk_embeddings')
    op.drop_table('chunk_embeddings')
    op.drop_index(op.f('ix_tables_version_id'), table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_ingestion_events_run_id'), table_name='ingestion_events')
    op.drop_table('ingestion_events')
    op.drop_index(op.f('ix_figures_version_id'), table_name='figures')
    op.drop_table('figures')
    op.drop_index(op.f('ix_cross_references_version_id'), table_name='cross_references')
    op.drop_index(op.f('ix_cross_references_from_section_id'), table_name='cross_references')
    op.drop_table('cross_references')
    op.drop_index('ix_chunks_version_sha', table_name='chunks')
    op.drop_index(op.f('ix_chunks_version_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_section_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_sections_version_ordinal', table_name='sections')
    op.drop_index(op.f('ix_sections_version_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_content_sha256'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_ingestion_runs_status'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_source_key'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index('ix_regulation_versions_status_valid', table_name='regulation_versions')
    op.drop_index(op.f('ix_regulation_versions_status'), table_name='regulation_versions')
    op.drop_index(op.f('ix_regulation_versions_regulation_id'), table_name='regulation_versions')
    op.drop_table('regulation_versions')
    op.drop_index(op.f('ix_user_feedback_trace_id'), table_name='user_feedback')
    op.drop_table('user_feedback')
    op.drop_index(op.f('ix_source_artifacts_source_key'), table_name='source_artifacts')
    op.drop_table('source_artifacts')
    op.drop_table('regulations')
    op.drop_table('query_traces')
    op.drop_index(op.f('ix_evaluation_cases_query_type'), table_name='evaluation_cases')
    op.drop_index(op.f('ix_evaluation_cases_dataset_version'), table_name='evaluation_cases')
    op.drop_table('evaluation_cases')
    # ### end Alembic commands ###
