"""copilot conversation persistence

Revision ID: 035d2ebc4f22
Revises: 9043dcc7b16e
Create Date: 2026-08-13 08:18:26.618056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # required by the `embeddings.embedding` Vector column
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '035d2ebc4f22'
down_revision: Union[str, Sequence[str], None] = '9043dcc7b16e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copilot_conversations',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_conversations_investigation_id'), 'copilot_conversations', ['investigation_id'], unique=True)
    op.create_table('copilot_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unknowns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_degraded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['copilot_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_messages_conversation_id'), 'copilot_messages', ['conversation_id'], unique=False)
    op.create_table('copilot_tool_calls',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['copilot_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_tool_calls_message_id'), 'copilot_tool_calls', ['message_id'], unique=False)
    op.create_foreign_key('fk_artifacts_simulation_run_id', 'artifacts', 'simulation_runs', ['simulation_run_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_artifacts_simulation_run_id', 'artifacts', type_='foreignkey')
    op.drop_index(op.f('ix_copilot_tool_calls_message_id'), table_name='copilot_tool_calls')
    op.drop_table('copilot_tool_calls')
    op.drop_index(op.f('ix_copilot_messages_conversation_id'), table_name='copilot_messages')
    op.drop_table('copilot_messages')
    op.drop_index(op.f('ix_copilot_conversations_investigation_id'), table_name='copilot_conversations')
    op.drop_table('copilot_conversations')
    # ### end Alembic commands ###
