"""cae_lsdyna_structured_entities

Revision ID: 564db6348063
Revises: 035d2ebc4f22
Create Date: 2026-08-13 12:12:56.315733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # required by the `embeddings.embedding` Vector column


# revision identifiers, used by Alembic.
revision: str = '564db6348063'
down_revision: Union[str, Sequence[str], None] = '035d2ebc4f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cae_decks',
    sa.Column('knowledge_source_id', sa.UUID(), nullable=False),
    sa.Column('deck_key', sa.Text(), nullable=False),
    sa.Column('main_file_relpath', sa.Text(), nullable=False),
    sa.Column('include_status', sa.Text(), nullable=False),
    sa.Column('parser_version', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_source_id'], ['knowledge_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck_key')
    )
    op.create_index(op.f('ix_cae_decks_knowledge_source_id'), 'cae_decks', ['knowledge_source_id'], unique=False)
    op.create_table('cae_files',
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('relpath', sa.Text(), nullable=False),
    sa.Column('archive_member_path', sa.Text(), nullable=True),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['cae_decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cae_files_deck_id'), 'cae_files', ['deck_id'], unique=False)
    op.create_table('cae_contacts',
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('contact_type', sa.Text(), nullable=True),
    sa.Column('ssid', sa.Integer(), nullable=True),
    sa.Column('msid', sa.Integer(), nullable=True),
    sa.Column('parse_status', sa.Text(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('raw_hash', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['cae_decks.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['cae_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cae_contacts_deck_id'), 'cae_contacts', ['deck_id'], unique=False)
    op.create_index(op.f('ix_cae_contacts_file_id'), 'cae_contacts', ['file_id'], unique=False)
    op.create_table('cae_controls',
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('control_type', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.Text(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('raw_hash', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['cae_decks.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['cae_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cae_controls_deck_id'), 'cae_controls', ['deck_id'], unique=False)
    op.create_index(op.f('ix_cae_controls_file_id'), 'cae_controls', ['file_id'], unique=False)
    op.create_table('cae_databases',
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('database_type', sa.Text(), nullable=True),
    sa.Column('dt', sa.Float(), nullable=True),
    sa.Column('parse_status', sa.Text(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('raw_hash', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['cae_decks.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['cae_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cae_databases_deck_id'), 'cae_databases', ['deck_id'], unique=False)
    op.create_index(op.f('ix_cae_databases_file_id'), 'cae_databases', ['file_id'], unique=False)
    op.create_table('cae_includes',
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('parent_file_id', sa.UUID(), nullable=False),
    sa.Column('target_as_written', sa.Text(), nullable=False),
    sa.Column('resolved_file_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['cae_decks.id'], ),
    sa.ForeignKeyConstraint(['parent_file_id'], ['cae_files.id'], ),
    sa.ForeignKeyConstraint(['resolved_file_id'], ['cae_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cae_includes_deck_id'), 'cae_includes', ['deck_id'], unique=False)
    op.create_index(op.f('ix_cae_includes_parent_file_id'), 'cae_includes', ['parent_file_id'], unique=False)
    op.create_table('cae_keywords',
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('root', sa.Text(), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('raw_hash', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['cae_decks.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['cae_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cae_keywords_deck_id'), 'cae_keywords', ['deck_id'], unique=False)
    op.create_index(op.f('ix_cae_keywords_file_id'), 'cae_keywords', ['file_id'], unique=False)
    op.create_index(op.f('ix_cae_keywords_keyword'), 'cae_keywords', ['keyword'], unique=False)
    op.create_table('cae_materials',
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('mat_type', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.Text(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('raw_hash', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['cae_decks.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['cae_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cae_materials_deck_id'), 'cae_materials', ['deck_id'], unique=False)
    op.create_index(op.f('ix_cae_materials_file_id'), 'cae_materials', ['file_id'], unique=False)
    op.create_index(op.f('ix_cae_materials_material_id'), 'cae_materials', ['material_id'], unique=False)
    op.create_table('cae_parts',
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('parse_status', sa.Text(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('raw_hash', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['cae_decks.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['cae_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cae_parts_deck_id'), 'cae_parts', ['deck_id'], unique=False)
    op.create_index(op.f('ix_cae_parts_file_id'), 'cae_parts', ['file_id'], unique=False)
    op.create_index(op.f('ix_cae_parts_part_id'), 'cae_parts', ['part_id'], unique=False)
    op.create_table('cae_sections',
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('section_type', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.Text(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('raw_hash', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['cae_decks.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['cae_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cae_sections_deck_id'), 'cae_sections', ['deck_id'], unique=False)
    op.create_index(op.f('ix_cae_sections_file_id'), 'cae_sections', ['file_id'], unique=False)
    op.create_index(op.f('ix_cae_sections_section_id'), 'cae_sections', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cae_sections_section_id'), table_name='cae_sections')
    op.drop_index(op.f('ix_cae_sections_file_id'), table_name='cae_sections')
    op.drop_index(op.f('ix_cae_sections_deck_id'), table_name='cae_sections')
    op.drop_table('cae_sections')
    op.drop_index(op.f('ix_cae_parts_part_id'), table_name='cae_parts')
    op.drop_index(op.f('ix_cae_parts_file_id'), table_name='cae_parts')
    op.drop_index(op.f('ix_cae_parts_deck_id'), table_name='cae_parts')
    op.drop_table('cae_parts')
    op.drop_index(op.f('ix_cae_materials_material_id'), table_name='cae_materials')
    op.drop_index(op.f('ix_cae_materials_file_id'), table_name='cae_materials')
    op.drop_index(op.f('ix_cae_materials_deck_id'), table_name='cae_materials')
    op.drop_table('cae_materials')
    op.drop_index(op.f('ix_cae_keywords_keyword'), table_name='cae_keywords')
    op.drop_index(op.f('ix_cae_keywords_file_id'), table_name='cae_keywords')
    op.drop_index(op.f('ix_cae_keywords_deck_id'), table_name='cae_keywords')
    op.drop_table('cae_keywords')
    op.drop_index(op.f('ix_cae_includes_parent_file_id'), table_name='cae_includes')
    op.drop_index(op.f('ix_cae_includes_deck_id'), table_name='cae_includes')
    op.drop_table('cae_includes')
    op.drop_index(op.f('ix_cae_databases_file_id'), table_name='cae_databases')
    op.drop_index(op.f('ix_cae_databases_deck_id'), table_name='cae_databases')
    op.drop_table('cae_databases')
    op.drop_index(op.f('ix_cae_controls_file_id'), table_name='cae_controls')
    op.drop_index(op.f('ix_cae_controls_deck_id'), table_name='cae_controls')
    op.drop_table('cae_controls')
    op.drop_index(op.f('ix_cae_contacts_file_id'), table_name='cae_contacts')
    op.drop_index(op.f('ix_cae_contacts_deck_id'), table_name='cae_contacts')
    op.drop_table('cae_contacts')
    op.drop_index(op.f('ix_cae_files_deck_id'), table_name='cae_files')
    op.drop_table('cae_files')
    op.drop_index(op.f('ix_cae_decks_knowledge_source_id'), table_name='cae_decks')
    op.drop_table('cae_decks')
    # ### end Alembic commands ###
