"""document_page_status

Revision ID: 6e0faa0ca413
Revises: 564db6348063
Create Date: 2026-08-13 14:34:21.547393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # required by the `embeddings.embedding` Vector column


# revision identifiers, used by Alembic.
revision: str = '6e0faa0ca413'
down_revision: Union[str, Sequence[str], None] = '564db6348063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing rows honestly: every document_pages
    # row that already exists genuinely did complete text extraction
    # (ingest_document() only persists a page after extract_pages()
    # succeeds) — EXTRACTED is the true status for that data, not a
    # placeholder. New rows going forward set status explicitly in code.
    op.add_column(
        'document_pages',
        sa.Column('status', sa.Text(), nullable=False, server_default='EXTRACTED'),
    )
    op.alter_column('document_pages', 'status', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_pages', 'status')
    # ### end Alembic commands ###
