"""initial domain schema

Revision ID: 9043dcc7b16e
Revises: 
Create Date: 2026-08-12 23:25:24.570462

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9043dcc7b16e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('simulation_run_id', sa.UUID(), nullable=True),
    sa.Column('artifact_type', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], name='fk_artifacts_simulation_run_id', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_index(op.f('ix_artifacts_simulation_run_id'), 'artifacts', ['simulation_run_id'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('source_key', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('authority_level', sa.Text(), nullable=False),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key')
    )
    op.create_table('organizations',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_definitions',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Text(), nullable=True),
    sa.Column('source_standard', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name', name='uq_signal_definitions_canonical_name')
    )
    op.create_table('source_snapshots',
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('documents',
    sa.Column('knowledge_source_id', sa.UUID(), nullable=False),
    sa.Column('document_key', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('document_type', sa.Text(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_source_id'], ['knowledge_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_key')
    )
    op.create_index(op.f('ix_documents_knowledge_source_id'), 'documents', ['knowledge_source_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('source_artifact_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('components',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('component_type', sa.Text(), nullable=False),
    sa.Column('parent_component_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_project_id'), 'components', ['project_id'], unique=False)
    op.create_table('document_revisions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('revision_label', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('source_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('extractor', sa.Text(), nullable=True),
    sa.Column('extractor_version', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_revisions_document_id'), 'document_revisions', ['document_id'], unique=False)
    op.create_table('investigations',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('primary_metric_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_project_id'), 'investigations', ['project_id'], unique=False)
    op.create_index(op.f('ix_investigations_state'), 'investigations', ['state'], unique=False)
    op.create_table('processing_steps',
    sa.Column('processing_job_id', sa.UUID(), nullable=False),
    sa.Column('step_name', sa.Text(), nullable=False),
    sa.Column('software', sa.Text(), nullable=True),
    sa.Column('software_version', sa.Text(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_hashes', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('output_hashes', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_steps_processing_job_id'), 'processing_steps', ['processing_job_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('programme', sa.Text(), nullable=True),
    sa.Column('vehicle_type', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_project_id'), 'vehicles', ['project_id'], unique=False)
    op.create_table('claims',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_investigation_id'), 'claims', ['investigation_id'], unique=False)
    op.create_table('comparability_assessments',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('evidence_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparability_assessments_investigation_id'), 'comparability_assessments', ['investigation_id'], unique=False)
    op.create_table('component_revisions',
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.Text(), nullable=False),
    sa.Column('source_artifact_id', sa.UUID(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_revisions_component_id'), 'component_revisions', ['component_id'], unique=False)
    op.create_table('configuration_diffs',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('run_a_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('run_b_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_status', sa.Text(), nullable=False),
    sa.Column('change_classification', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_diffs_investigation_id'), 'configuration_diffs', ['investigation_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('document_revision_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('page_image_uri', sa.Text(), nullable=True),
    sa.Column('text_quality', sa.Double(), nullable=True),
    sa.Column('layout_quality', sa.Double(), nullable=True),
    sa.Column('ocr_used', sa.Boolean(), nullable=False),
    sa.Column('ocr_confidence', sa.Double(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_revision_id'], ['document_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_pages_document_revision_id'), 'document_pages', ['document_revision_id'], unique=False)
    op.create_table('document_sections',
    sa.Column('document_revision_id', sa.UUID(), nullable=False),
    sa.Column('parent_section_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('section_number', sa.Text(), nullable=True),
    sa.Column('start_page', sa.Integer(), nullable=True),
    sa.Column('end_page', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_revision_id'], ['document_revisions.id'], ),
    sa.ForeignKeyConstraint(['parent_section_id'], ['document_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_sections_document_revision_id'), 'document_sections', ['document_revision_id'], unique=False)
    op.create_table('engineer_reviews',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engineer_reviews_investigation_id'), 'engineer_reviews', ['investigation_id'], unique=False)
    op.create_table('evidence',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_locator', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculation_version', sa.Text(), nullable=True),
    sa.Column('source_hash', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_investigation_id'), 'evidence', ['investigation_id'], unique=False)
    op.create_table('findings',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_investigation_id'), 'findings', ['investigation_id'], unique=False)
    op.create_table('hypotheses',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('confidence_basis', sa.Text(), nullable=True),
    sa.Column('affected_components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_isolation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypotheses_investigation_id'), 'hypotheses', ['investigation_id'], unique=False)
    op.create_table('investigation_metrics',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('signal_definition_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['signal_definition_id'], ['signal_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_metrics_investigation_id'), 'investigation_metrics', ['investigation_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('source_artifact_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_vehicle_id'), 'model_versions', ['vehicle_id'], unique=False)
    op.create_table('recommended_actions',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommended_actions_investigation_id'), 'recommended_actions', ['investigation_id'], unique=False)
    op.create_table('controlled_comparison_requests',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('hypothesis_id', sa.UUID(), nullable=False),
    sa.Column('requested_change', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('controlled_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controlled_comparison_requests_investigation_id'), 'controlled_comparison_requests', ['investigation_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_revision_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('page_id', sa.UUID(), nullable=True),
    sa.Column('parent_chunk_id', sa.UUID(), nullable=True),
    sa.Column('chunk_type', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('source_locator', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_revision_id'], ['document_revisions.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.id'], ),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_revision_id'), 'document_chunks', ['document_revision_id'], unique=False)
    op.create_table('document_equations',
    sa.Column('document_revision_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('equation_number', sa.Text(), nullable=True),
    sa.Column('latex', sa.Text(), nullable=True),
    sa.Column('image_uri', sa.Text(), nullable=True),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_method', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_revision_id'], ['document_revisions.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_equations_document_revision_id'), 'document_equations', ['document_revision_id'], unique=False)
    op.create_table('document_figures',
    sa.Column('document_revision_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('figure_number', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('image_uri', sa.Text(), nullable=False),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('figure_type', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_revision_id'], ['document_revisions.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_figures_document_revision_id'), 'document_figures', ['document_revision_id'], unique=False)
    op.create_table('document_tables',
    sa.Column('document_revision_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('table_number', sa.Text(), nullable=True),
    sa.Column('markdown_uri', sa.Text(), nullable=True),
    sa.Column('json_uri', sa.Text(), nullable=True),
    sa.Column('image_uri', sa.Text(), nullable=True),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_method', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Double(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_revision_id'], ['document_revisions.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_tables_document_revision_id'), 'document_tables', ['document_revision_id'], unique=False)
    op.create_table('evidence_contradictions',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('evidence_a_id', sa.UUID(), nullable=False),
    sa.Column('evidence_b_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_a_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['evidence_b_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_contradictions_investigation_id'), 'evidence_contradictions', ['investigation_id'], unique=False)
    op.create_table('hypothesis_evidence_links',
    sa.Column('hypothesis_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('relationship', sa.Text(), nullable=False),
    sa.Column('weight', sa.Double(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_evidence_links_evidence_id'), 'hypothesis_evidence_links', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_hypothesis_evidence_links_hypothesis_id'), 'hypothesis_evidence_links', ['hypothesis_id'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('parent_run_id', sa.UUID(), nullable=True),
    sa.Column('solver', sa.Text(), nullable=True),
    sa.Column('solver_version', sa.Text(), nullable=True),
    sa.Column('dummy_version', sa.Text(), nullable=True),
    sa.Column('impact_type', sa.Text(), nullable=True),
    sa.Column('impact_speed', sa.Double(), nullable=True),
    sa.Column('barrier', sa.Text(), nullable=True),
    sa.Column('seat_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('restraint_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_processing_version', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('quality_status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['parent_run_id'], ['simulation_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index(op.f('ix_simulation_runs_model_version_id'), 'simulation_runs', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_simulation_runs_project_id'), 'simulation_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_simulation_runs_vehicle_id'), 'simulation_runs', ['vehicle_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embeddings_chunk_id'), 'embeddings', ['chunk_id'], unique=False)
    op.create_table('investigation_runs',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_runs_investigation_id'), 'investigation_runs', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigation_runs_simulation_run_id'), 'investigation_runs', ['simulation_run_id'], unique=False)
    op.create_table('quality_gate_results',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('check_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('threshold', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_gate_results_investigation_id'), 'quality_gate_results', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_quality_gate_results_simulation_run_id'), 'quality_gate_results', ['simulation_run_id'], unique=False)
    op.create_table('signals',
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('signal_definition_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source_channel', sa.Text(), nullable=True),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('sampling_rate', sa.Double(), nullable=True),
    sa.Column('start_time', sa.Double(), nullable=True),
    sa.Column('end_time', sa.Double(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('processing_version_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_definition_id'], ['signal_definitions.id'], ),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_signal_definition_id'), 'signals', ['signal_definition_id'], unique=False)
    op.create_index(op.f('ix_signals_simulation_run_id'), 'signals', ['simulation_run_id'], unique=False)
    op.create_table('signal_analyses',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('signal_definition_id', sa.UUID(), nullable=False),
    sa.Column('run_a_signal_id', sa.UUID(), nullable=False),
    sa.Column('run_b_signal_id', sa.UUID(), nullable=False),
    sa.Column('alignment_method', sa.Text(), nullable=True),
    sa.Column('filtering_method', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('algorithm_version', sa.Text(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['run_a_signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['run_b_signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['signal_definition_id'], ['signal_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_analyses_investigation_id'), 'signal_analyses', ['investigation_id'], unique=False)
    op.create_table('signal_features',
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('feature_name', sa.Text(), nullable=False),
    sa.Column('value', sa.Double(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('algorithm_version', sa.Text(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_features_signal_id'), 'signal_features', ['signal_id'], unique=False)
    op.create_table('signal_transformations',
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('transformation_type', sa.Text(), nullable=False),
    sa.Column('algorithm_version', sa.Text(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_signal_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['input_signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_transformations_signal_id'), 'signal_transformations', ['signal_id'], unique=False)
    op.create_table('analysis_events',
    sa.Column('signal_analysis_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('time_ms', sa.Double(), nullable=False),
    sa.Column('algorithm_version', sa.Text(), nullable=False),
    sa.Column('threshold', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('window', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('alignment_method', sa.Text(), nullable=True),
    sa.Column('source_signal_id', sa.UUID(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_analysis_id'], ['signal_analyses.id'], ),
    sa.ForeignKeyConstraint(['source_signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_events_signal_analysis_id'), 'analysis_events', ['signal_analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_events_signal_analysis_id'), table_name='analysis_events')
    op.drop_table('analysis_events')
    op.drop_index(op.f('ix_signal_transformations_signal_id'), table_name='signal_transformations')
    op.drop_table('signal_transformations')
    op.drop_index(op.f('ix_signal_features_signal_id'), table_name='signal_features')
    op.drop_table('signal_features')
    op.drop_index(op.f('ix_signal_analyses_investigation_id'), table_name='signal_analyses')
    op.drop_table('signal_analyses')
    op.drop_index(op.f('ix_signals_simulation_run_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_signal_definition_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_quality_gate_results_simulation_run_id'), table_name='quality_gate_results')
    op.drop_index(op.f('ix_quality_gate_results_investigation_id'), table_name='quality_gate_results')
    op.drop_table('quality_gate_results')
    op.drop_index(op.f('ix_investigation_runs_simulation_run_id'), table_name='investigation_runs')
    op.drop_index(op.f('ix_investigation_runs_investigation_id'), table_name='investigation_runs')
    op.drop_table('investigation_runs')
    op.drop_index(op.f('ix_embeddings_chunk_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_simulation_runs_vehicle_id'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_project_id'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_model_version_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_hypothesis_evidence_links_hypothesis_id'), table_name='hypothesis_evidence_links')
    op.drop_index(op.f('ix_hypothesis_evidence_links_evidence_id'), table_name='hypothesis_evidence_links')
    op.drop_table('hypothesis_evidence_links')
    op.drop_index(op.f('ix_evidence_contradictions_investigation_id'), table_name='evidence_contradictions')
    op.drop_table('evidence_contradictions')
    op.drop_index(op.f('ix_document_tables_document_revision_id'), table_name='document_tables')
    op.drop_table('document_tables')
    op.drop_index(op.f('ix_document_figures_document_revision_id'), table_name='document_figures')
    op.drop_table('document_figures')
    op.drop_index(op.f('ix_document_equations_document_revision_id'), table_name='document_equations')
    op.drop_table('document_equations')
    op.drop_index(op.f('ix_document_chunks_document_revision_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_controlled_comparison_requests_investigation_id'), table_name='controlled_comparison_requests')
    op.drop_table('controlled_comparison_requests')
    op.drop_index(op.f('ix_recommended_actions_investigation_id'), table_name='recommended_actions')
    op.drop_table('recommended_actions')
    op.drop_index(op.f('ix_model_versions_vehicle_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_investigation_metrics_investigation_id'), table_name='investigation_metrics')
    op.drop_table('investigation_metrics')
    op.drop_index(op.f('ix_hypotheses_investigation_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_findings_investigation_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_evidence_investigation_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_engineer_reviews_investigation_id'), table_name='engineer_reviews')
    op.drop_table('engineer_reviews')
    op.drop_index(op.f('ix_document_sections_document_revision_id'), table_name='document_sections')
    op.drop_table('document_sections')
    op.drop_index(op.f('ix_document_pages_document_revision_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_configuration_diffs_investigation_id'), table_name='configuration_diffs')
    op.drop_table('configuration_diffs')
    op.drop_index(op.f('ix_component_revisions_component_id'), table_name='component_revisions')
    op.drop_table('component_revisions')
    op.drop_index(op.f('ix_comparability_assessments_investigation_id'), table_name='comparability_assessments')
    op.drop_table('comparability_assessments')
    op.drop_index(op.f('ix_claims_investigation_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_vehicles_project_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_processing_steps_processing_job_id'), table_name='processing_steps')
    op.drop_table('processing_steps')
    op.drop_index(op.f('ix_investigations_state'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_project_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_document_revisions_document_id'), table_name='document_revisions')
    op.drop_table('document_revisions')
    op.drop_index(op.f('ix_components_project_id'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_documents_knowledge_source_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('source_snapshots')
    op.drop_table('signal_definitions')
    op.drop_table('organizations')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_artifacts_simulation_run_id'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
